version: "3.8"
services:
  orchestration:
    networks:
      - default
    build:
      context: ../src/orchestration
      dockerfile: ./Dockerfile
    working_dir: /workspaces/orchestration
    stdin_open: true
    tty: true
    volumes:
      - ../src/orchestration:/workspaces/orchestration
    ports:
      - 3000:3000
  workspace:
    networks:
      - default
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/Big-Data/
    stdin_open: true
    tty: true
    depends_on:
      - orchestration
    working_dir: /workspaces/Big-Data
networks:
  default:
    driver: bridge
  servers_default:
    external: true
